// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtHGgClsv8dx0QKs15WteJiW6IZ-Rmt2E',
    appId: '1:550018547929:web:6e4e5571b2bec7b47ffec8',
    messagingSenderId: '550018547929',
    projectId: 'flutter-keep-my-notes',
    authDomain: 'flutter-keep-my-notes.firebaseapp.com',
    storageBucket: 'flutter-keep-my-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmOI9T5GOj21sAgL1m76TIn64fyzTUqv0',
    appId: '1:550018547929:android:f3da3b53d83b1a307ffec8',
    messagingSenderId: '550018547929',
    projectId: 'flutter-keep-my-notes',
    storageBucket: 'flutter-keep-my-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5XDReXtWgrKsboHac8l_fEWj21l6CXIA',
    appId: '1:550018547929:ios:5e3d5e2cafd553697ffec8',
    messagingSenderId: '550018547929',
    projectId: 'flutter-keep-my-notes',
    storageBucket: 'flutter-keep-my-notes.appspot.com',
    iosClientId: '550018547929-e8rd7vml44ng5iji2pslhs5ahll61ta7.apps.googleusercontent.com',
    iosBundleId: 'com.example.keepNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5XDReXtWgrKsboHac8l_fEWj21l6CXIA',
    appId: '1:550018547929:ios:70dbe7d5895a7aef7ffec8',
    messagingSenderId: '550018547929',
    projectId: 'flutter-keep-my-notes',
    storageBucket: 'flutter-keep-my-notes.appspot.com',
    iosClientId: '550018547929-fog24539t09pihbeahem9f23pcm31aui.apps.googleusercontent.com',
    iosBundleId: 'com.example.keepNotes.RunnerTests',
  );
}
